# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20170919_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
