"""
Django settings for HugoBoulengerProduction project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Where media files are located
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# URL extension to access media files
MEDIA_URL = '/media/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'b925)kstvtd!ssdnx1%pa78kuh=pwf(0(zynyb#+pk47(^7e%#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# TODO: Static problems on debug false

ALLOWED_HOSTS = ['localhost']

ADMINS = (
    ('Boris Ghidaglia', 'boris.ghidaglia@edu.esiee.fr'),
    ('Augustin Prolongeau', 'augustin.pro@gmail.com'),
)
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'paypal.standard.ipn',
    'DATA',
    'bio',
    'portfolios',
    'videos',
    'news',
    'shop',
    'home',
    'subscribe',
    'contact',
    'ordered_model',
]

PAYPAL_TEST = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'HugoBoulengerProduction.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],

            'libraries':{
            'format_socials': 'DATA.templatetags.socials',
            'photos_sub_menu': 'portfolios.templatetags.photos_sub_menu',
            'videos_sub_menu': 'videos.templatetags.videos_sub_menu',
            }

        },
    },
]

WSGI_APPLICATION = 'HugoBoulengerProduction.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SERVER_EMAIL = 'admin@hugoboulenger.com' # NOTE: Only for website error admin mails
EMAIL_HOST = 'smtp.hugoboulenger.com'
EMAIL_HOST_USER = 'test@hugoboulenger.com'
EMAIL_HOST_PASSWORD = 'lae3cestdeleau'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

# Where the statics files are located
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

SCRIPTS_DIRS = [
    os.path.join(BASE_DIR, 'scripts'),
]

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)
