# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hd', models.ImageField(upload_to='DATA/hd/', verbose_name='Photo haute définition')),
                ('ld', models.ImageField(upload_to='DATA/ld/', verbose_name='Photo basse définition')),
                ('key', models.CharField(blank=True, max_length=16, unique=True)),
                ('title', models.CharField(default='', max_length=40)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(to='DATA.Tag'),
        ),
    ]
