# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='subtitle',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
