# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0002_bio_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
