# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0005_image_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='portrait',
        ),
        migrations.AddField(
            model_name='bio',
            name='image',
            field=models.ImageField(default='media/bio/1.jpg', upload_to='bio/'),
            preserve_default=False,
        ),
    ]
